//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEFWeekly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string ISBN { get; set; }
        public string Title { get; set; }
        public Nullable<int> YearPublished { get; set; }
        public string AuthorID { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public string AuthorTFN { get; set; }
    }
}
